### ISSUE TITLE
Status menu not showing after opening the list of EVCs

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/ui#110]
Hi,

If you click on mef_eline and then List EVCs, then you click to see the Status Menu, it will be hidden by the Mef_eline's list evc. (it looks like the status menu didnt raise an event to minimize the other panels)

**Comment by viniarck** [comment]
Related backported issues and then we can use that one here for the general fix:

https://github.com/kytos-ng/ui/issues/112
https://github.com/kytos-ng/ui/issues/113
