### ISSUE TITLE
Fix `<k-input>` `title` and `tooltip` Parameters

### ISSUE THREAD

**Issue by HeriLFIU** [kytos-ng/ui#52]
The vue.js kytos component `<k-input>` does not seem to be functioning properly as the `title` and `tooltip` parameters are not functioning. Whenever one is given a value, the appropriate title and tooltip are not displayed. Because of this, it needs fixing, and maybe other similar parameters in other components could have the same issue, but I have yet to encounter them.

**Comment by viniarck** [comment]
@HeriLFIU will work on this one
