### ISSUE TITLE
Bundle napps with webpack

### ISSUE THREAD

**Issue by HeriLFIU** [kytos-ng/ui#88]
## Issue
Napps are currently being loaded in at runtime and can't be tested properly, so they need to be bundled in with current/main UI.
## Current Fix
Steps:

- Napp UI should be easily downloadable via something like a bash script.
- Code should be modified to register napp components at compile time instead of at runtime to allow for bundling of napps.
- You should be able to switch between loading the napp UI at runtime and bundling them at compile time, depending on which mode/configuration you are using (production or development). This could be accomplished by utilizing the webpack `DefinePlugin`.
## Parent Issue
https://github.com/kytos-ng/ui/issues/84#issue-2543577425

**Comment by italovalcy** [comment]
Hi @HeriLFIU, even if you bundle the Napps together with the UI, since all the Napps strongly depend on Kytos REST APIs, wouldn't that impact the tests anyway? I'm not sure how you will benefit from having the Napps bundled with the UI core but not having all APIs available. I apologize in advance if I missed something, but it may be something to keep in mind.

**Comment by HeriLFIU** [comment]
Hello @italovalcy, Yes, that is true. I had originally thought that the only way to test the UI with the Vue compatibility layer was in development mode with the dev server. I had also thought that it would be the fastest way of testing since I could just save and view the changes. But, after working with Webpack today, I realized that I could enable it on production as well and get the same results. Some of the code written is not yet lost, as it can probably be used within the other async task to bundle the napps individually and asynchronously load them at runtime. I was also able to read the vue compat documentation, so I should be able to change some of the code much quicker.
